### ISSUE TITLE
Latest 1.2.1 authenticode signed with SHA1 digest

### ISSUE THREAD

**Issue by vcsjones** [Yubico/yubikey-piv-manager#10]
The Windows version of the prebuilt binary for 1.2.1 is signed with a SHA256 certificate, but the file digest algorithm of the signature is still SHA1. Likewise, so is the timestamp digest algorithm.

It appears that the latest build of Windows 10 (on the fast ring) no longer allows signatures where the file digest algorithm is SHA1, causing it to warn that the signature is invalid.

![screen shot 2016-04-10 at 8 31 35 pm](https://cloud.githubusercontent.com/assets/361677/14414138/b487e2bc-ff5b-11e5-82a7-83e7af4ca130.png)

Regardless of whether or not this change reaches Windows stable, I'd recommend re-releasing this with a dual SHA1 / SHA256 signature.

**Comment by dainnilsson** [comment]
Thanks, I suspect this affects several of our Windows builds, which should all be signed using SHA256. Should be a simple fix...
