### ISSUE TITLE
setup for macOS deleted my RSA certificate

### ISSUE THREAD

**Issue by roryk** [Yubico/yubikey-piv-manager#15]
Hey ya'll,

I was using a RSA certificate for SSH, and I was totally surprised by 'setup for macOS' nuking it and replacing it with a ECCP256 certificate instead, which openSSH doesn't support. Maybe a warning that it is going to do that would be good?

**Comment by dagheyman** [comment]
Yes, I agree, we should add a confirmation dialog when existing certificates are about to be overwritten. Will be included in the next release.

**Comment by roryk** [comment]
Thanks for the super fast response Dag!
