### ISSUE TITLE
CertificateTemplate need clarification

### ISSUE THREAD

**Issue by c3ph3us** [Yubico/yubikey-piv-manager#2]
Certreq Template
Value to use in CertificateTemplate parameter when calling certreq.exe.
key
certreq_template
type
string

FORMAT OF STRING / SPECIFICATION ? 

example: 
certreq -submit -attrib "CertificateTemplate:Domaincontroller\nSAN:DNS=w2k3bodc.contoso.com" dcname.req dcname.cer dcname.p7b 

is it STRING? -attrib "CertificateTemplate:STRING"

**Comment by dainnilsson** [comment]
Yes, that is correct.
