### ISSUE TITLE
PIV Manager not installing as an option in Start Menu

### ISSUE THREAD

**Issue by dgyubi** [Yubico/yubikey-piv-manager#25]
On a fresh installation of Windows 10, PIV Manager will not show up as an application in the Start Menu.  Due to this, the application can not be pinned to Start or Taskbar "normally". Note, it will show up as a Startup option and under the Program Files. Have also done an uninstall/install with varying "admin" rights as well but shows the same issue.

Variables:
1) Windows 10 Pro, version 1703 (fresh installation)
2) PIV Manager, version 1.4.2 Windows
3) Physical machine, Dell Latitude E7270

**Comment by nicyubi** [comment]
Also seen this with a fresh Win 10 1703 install and a fresh 2012 Server install and had colleague report same problem.

Can run Manager manually and all seems to work, just isn't registered on the start menu or as an app that can be found by search etc.

**Comment by dagheyman** [comment]
Reproduced, seems to be an issue with the installer. I'll look into it.

**Comment by dagheyman** [comment]
I released a new installer for 1.4.2 for windows, 1.4.2c, which should resolve this issue.
https://developers.yubico.com/yubikey-piv-manager/Releases/yubikey-piv-manager-1.4.2c-win.exe

**Comment by nicyubi** [comment]
appears to work fine for me

Thanks

Nic

--
*Nic Sarginson*
Solutions UK&I | *Yubico* <http://www.yubico.com/>
Phone: +44 7957 598686
Skype: nic.sarginson

**Comment by nicyubi** [comment]
Actually on Win10 whilst it installs as a seachable desktop app it doesn't
appear in the start menu list under Yubico, the uninstaller does but not
the PIV Manager

--
*Nic Sarginson*
Solutions UK&I | *Yubico* <http://www.yubico.com/>
Phone: +44 7957 598686
Skype: nic.sarginson

**Comment by nicyubi** [comment]
Update - that just appears to be on a machine where the old version was
installed. a fresh install on a machine that never had it installed seems
fine

--
*Nic Sarginson*
Solutions UK&I | *Yubico* <http://www.yubico.com/>
Phone: +44 7957 598686
Skype: nic.sarginson
