### ISSUE TITLE
YubiKey PIV Manager 1.4.2 can't detect YubiKey 4 in Win10 1709

### ISSUE THREAD

**Issue by patrickgardella** [Yubico/yubikey-piv-manager#27]
Good morning!

Due to my work, I'm running a Windows Insider Build on VMWare Fusion using an Apple USB3 adapter. The PIV Manager doesn't detect the YubiKey4.  I tried all the steps in the [other issue](https://forum.yubico.com/viewtopic.php?f=35&t=2642) with no success.  

Windows 10 Pro version 1709 build 16299.0
PIV Manager 1.4.2c

![image](https://user-images.githubusercontent.com/6595897/31054193-6f1bf632-a67b-11e7-864c-169a74856489.png)

On the Mac side of things, it all works fine:

![image](https://user-images.githubusercontent.com/6595897/31054231-4532de7a-a67c-11e7-859d-14e919178b0c.png)

The YubiKey Smart Card is greyed out in the Device Manager.  I've tried removing the device and reinstalling it. I've tried removing all the USB devices and restarted.  And I've updated the Registry Key as noted in the other issue (which fixed it for the Creators Update). 

![image](https://user-images.githubusercontent.com/6595897/31054192-5a6c4476-a67b-11e7-94ff-b7a1ada405e7.png)

Any ideas?

**Comment by emlun** [comment]
Thank you for the report. Does [YubiKey Manager][ykman-qt] detect the YubiKey on your machine? If so, can you check if the command line tool can successfully run `ykman piv info`?

[ykman-qt]: https://github.com/Yubico/yubikey-manager-qt/releases/tag/yubikey-manager-qt-0.3.1

**Comment by patrickgardella** [comment]
It does not.

The CLI returns:
C:\Program Files (x86)\Yubico\YubiKey Manager>ykman piv info
Usage: ykman [OPTIONS] COMMAND [ARGS]...

Error: No YubiKey detected!

**Comment by emlun** [comment]
Does `ykman info` also output `Error: No YubiKey detected`? If so, have you checked that your VM engine is set up to forward the USB device through from the host OS to the Windows guest?

**Comment by patrickgardella** [comment]
`ykman info` returns `Error: No YubiKey detected`
 
It is set up to forward the USB device, and Windows detects it.  That's how the item in device manager was created.  But when I just looked, the Eject USB from the taskbar lists "Virtual USB CCID". I don't think that's normal, is it? 

I'm starting to think this is a VMWare issue, not a Yubico one.

**Comment by emlun** [comment]
Yes, at least it's not specific to yubikey-piv-manager. I've confirmed it works with [this Vagrant VM][vm] running in VirtualBox, you're welcome to try it yourself.

I'll close this issue for now. If anything new comes up, please reopen it and let us know!

[vm]: https://github.com/Yubico/yubikey-piv-manager/tree/master/vagrant/windows-user

**Comment by patrickgardella** [comment]
Thanks for the help!
