### ISSUE TITLE
PIN recommendations and requirements [Documentation]

### ISSUE THREAD

**Issue by My1** [Yubico/yubikey-piv-manager#29]
on your page
https://developers.yubico.com/yubikey-piv-manager/PIN_and_Management_Key.html
it states that 4 characters is required, which apparently is wrong in newer versions, where 6 is needed (and in older versions of the software the errors dont make sense if you try to initialize a newer yubi with a 4 digit pin or puk and yeah the update made it become 6 for whatever reason (slightly annoying because I like the 4 digit pin I used on my old key)

so in general the website should state the minlength is now six, and

"though it is recommended to only use those contained in the ASCII character set"

which contradicts what the program says as it says that it's recommended to only use numbers.

**Comment by emlun** [comment]
Thanks for pointing these things out! We'll get them fixed.
