### ISSUE TITLE
period of validity

### ISSUE THREAD

**Issue by c3ph3us** [Yubico/yubikey-piv-manager#3]
i wish to set up a period of validity for cert 
by default is one year

**Comment by c3ph3us** [comment]
?? hello

**Comment by dainnilsson** [comment]
Hi.
This feature is currently not supported.

**Comment by c3ph3us** [comment]
ok will u consider adding it ?

**Comment by dagheyman** [comment]
Support for this is now added and will be included in the upcoming release.
