### ISSUE TITLE
Please provide explicit install instructions for Red Hat Linux.

### ISSUE THREAD

**Issue by kirbyjason** [Yubico/yubikey-piv-manager#33]
From the README: "The recommended way to install this software including dependencies is by using the provided precompiled binaries for your platform." 

Usually installation instructions within README come with explicit instructions, such as,
./configure; make; make install.  Althought we have used these for years they are given to us again and again, possibly for the newcomers.  As it should be.

If there's a command or series of commands that I should be typing under RHEL6 to "install this software including the dependencies by using the provided precompiled binaries," please provide it.  

I've tested the install with Windows with no problem; neither OS X nor Ubuntu applies to my environment. I've untarred the yubikey-piv-manager-1.4.2 and see a bunch of python files. I would appreciate knowing how to finish this installation for Red Hat 6.

**Comment by emlun** [comment]
I'm sorry, we don't have instructions for RHEL6 prepared. The closest thing we have is the [development README][devrm], which instructs how to build the application in an Ubuntu VM. With some luck it might even be possible to run that build on an RHEL6 machine if you can get hold of the runtime dependencies. You're welcome to refer to the [development 
README][devrm] and the [VM provisioning script][provision] to work out what dependencies you need. Unfortunately it seems like PySide, and possibly other dependencies as well, aren't available in the RHEL6/CentOS6 repositories. I'm afraid we don't have the manpower to help you with this right now, but you're welcome to try.

Alternatively, if you don't need a GUI you could perhaps try one of the command line tools [YubiKey Manager][ykman] or [Yubico PIV tool][pivtool] instead.

[devrm]: https://github.com/Yubico/yubikey-piv-manager/blob/master/doc/development.adoc
[provision]: https://github.com/Yubico/yubikey-piv-manager/blob/master/vagrant/development/provision.sh
[ykman]: https://developers.yubico.com/yubikey-manager/
[pivtool]: https://developers.yubico.com/yubico-piv-tool/
