### ISSUE TITLE
Support for Qt5?

### ISSUE THREAD

**Issue by kbabioch** [Yubico/yubikey-piv-manager#37]
Currently the project requires PySide, which are bindings for Qt4. Are there any plans to migrate to Qt5 (PyOtherSide, PySide2), so no Qt4 dependencies will be pulled in?

**Comment by dagheyman** [comment]
Probably not for this specific tool. The current plan is to merge most of the functionality of this tool with YubiKey Manager (which uses PyOtherSide and Qt5) at some point. No ETA for that right now.
