### ISSUE TITLE
macOS problem change PIN to only contain numeric characters

### ISSUE THREAD

**Issue by alimov** [Yubico/yubikey-piv-manager#40]
Helo,
i have problem change PIN to ONLY numeric character on macOS. 

**my setup**
1. pair yubikey with macOS 
![snimek obrazovky 2018-05-10 v 8 27 42](https://user-images.githubusercontent.com/4499419/39855418-1cab267a-542c-11e8-90ea-5bfd539479cd.png)

click **YES**

2. insert corect ALPHANUMERIC PIN
![snimek obrazovky 2018-05-10 v 8 28 53](https://user-images.githubusercontent.com/4499419/39855489-6b215f7c-542c-11e8-90f5-c4ec28672909.png)

click **OK**

3. application warning - macOS requires only numeric PIN
![snimek obrazovky 2018-05-10 v 8 30 49](https://user-images.githubusercontent.com/4499419/39855538-9227755c-542c-11e8-886e-accda0260800.png)

click **YES**

4. insert corect ALPHANUMERIC PIN and new numeric PIN
![snimek obrazovky 2018-05-10 v 8 32 44](https://user-images.githubusercontent.com/4499419/39855593-d6a9b4a6-542c-11e8-9505-796eeaf9b835.png)

click **OK**

5. App warning PIN must contains ALPHANUMERIC and three  of the a-z, A-Z,0-9, special characters
![snimek obrazovky 2018-05-10 v 8 32 50](https://user-images.githubusercontent.com/4499419/39855623-eeb365b0-542c-11e8-8564-bf868faf7d71.png)

is not posible change PIN to only numeric pin ( but numeric PIN require mac OS )

How is my problem solved ?

info:
mac OS High SIERRA 10.13.4
yubikey piv manager 1.4.2e ( download last version from website)
![snimek obrazovky 2018-05-10 v 8 39 01](https://user-images.githubusercontent.com/4499419/39855792-a550d3a2-542d-11e8-9cce-f2d08768f46b.png)

**Comment by alimov** [comment]
ok i resolve this problem in app settings

![snimek obrazovky 2018-05-10 v 8 45 12](https://user-images.githubusercontent.com/4499419/39856046-be84387c-542e-11e8-838b-78602e5c349c.png)


by default is set enforce PIN/PUK?

after uncheck this feature  numeric PIN is possible to change.

**Comment by emlun** [comment]
Hi! Sorry for the late response, but I'm glad you managed to solve it.
