### ISSUE TITLE
Missing in Ubuntu PPA for Artful and later

### ISSUE THREAD

**Issue by steamraven** [Yubico/yubikey-piv-manager#42]
The main readme indicates you can install from the main Yubico PPA at https://launchpad.net/~yubico/+archive/ubuntu/stable

However, the repository does not have yubikey-piv-manager for Artful and more critically Bionic.

**Comment by emlun** [comment]
Hi! Sorry for being slow to respond. We're currently in the process of replacing YubiKey PIV Manager, so we don't plan to provide packages for these distributions.
