### ISSUE TITLE
Cannot set pin, error: can't concat bytes to str

### ISSUE THREAD

**Issue by opoplawski** [Yubico/yubikey-piv-manager#44]
Running on linux with python 3.4, I cannot set the PIN on a new yubikey.  I get:

can't concat bytes to str

**Comment by emlun** [comment]
Hi!

Unfortunately, YubiKey PIV Manager isn't compatible with Python 3 - you'll need to run it with Python 2. Alternatively, you could use the [`ykman` CLI][ykman] (which is Python 3 compatible) to change the PIN.

[ykman]: https://github.com/Yubico/yubikey-manager
