### ISSUE TITLE
Failing connection to Certificate Authority

### ISSUE THREAD

**Issue by softcat** [Yubico/yubikey-piv-manager#5]
Hello,

I'm trying to generate a new key signed by my certificate authority (Windows Server 2012 R2 CA) in a domain enviroment using the tool.

When opening the "Generate new key" dialogue it states that I do not have a connection to a CA which is not true. I looked into the code and you are parsing the result of "certutil.exe -dump" for a string "Entry". I'm working on localised version of Windows 10 (german) therefore this fails.

I came with generating a csr und using certreq from the commandline. Which comes to a second question. There is the option "Require PIN" in "Usage policy". I tried "Never" but I still beeing asked for the pin. Is this functional?

Many thanke and regards!

**Comment by ghost** [comment]
I can confirm this issue. Please fix it, there is a high need for me.
