### ISSUE TITLE
RSA 4096 is not offered for YubiKey 4

### ISSUE THREAD

**Issue by R-Adrian** [Yubico/yubikey-piv-manager#7]
YubiKey 4 supports RSA 4096 but the current version of PIV Manager for windows, v1.2.1 GUI and v.1.2.2 CLI does not offer RSA 4096 for generating self-signed certificates or signing requests.

**Comment by dainnilsson** [comment]
The YubiKey 4 supports RSA 4096 keys for use with OpenPGP. The PIV standard does not include RSA 4096 in its set of algorithms, and thus PIV on the YubiKey 4 does not support this.
