### ISSUE TITLE
GUI tool needs to set "Card Capability Container" for OSX support.

### ISSUE THREAD

**Issue by Davidllo** [Yubico/yubikey-piv-manager#9]
It looks as though the GUI tool is setting the CHUID, but not the CCC.  This means that Yubikeys will not work using Apple's "Smart card Services for Macintosh" PIV driver.

See the set-ccc and set-chuid actions in the command line tool.  Using the new set-ccc action fixes this problem.

Both CCC and CHUID are required for correctly functioning PIV cards.

Thanks!

**Comment by dainnilsson** [comment]
This will probably be in the next non-bugfix version (likely to be 1.3.0), as part of the initialization process (which is when the CHUID is set). No current ETA for the release.

**Comment by dagheyman** [comment]
Fixed and will be included in next release.
